---
# tasks file for setup_ec2_vpc

- name: Create a VPC
  ec2_vpc_net:
    name: "{{ vpc_name_tag }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ region }}"
    tags:
      module: "{{ boot_name }} ec2_vpc"
    tenancy: default
  register: vpc_data

- set_fact:
     newly_created_vpc_id: "{{ vpc_data.vpc.id }}"

