---
  - name: Set up default website on server
    hosts: tag_Type_redmine
    vars_files:
      - vars/vars_for_default_site.yml
    remote_user: ubuntu
    become: yes
    gather_facts: yes

    roles:
      - role: deploy_default_site
      - role: letsencrypt-ansible
        become: yes